### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by kkalle** [oaleeapp/SwiftEyes#6]
After running "pod install" (on Mac) as instructed, I get get the following errors and the installation fails. Can you help me out? I'm new to Cocoapods, Apple platform, etc.

Analyzing dependencies
Fetching podspec for `SwiftEyes` from `../`
Downloading dependencies
Installing OpenCV-Dynamic (3.2.3)
[!] /bin/bash -c 
set -e
git submodule init
git submodule update
python opencv/platforms/ios/build_framework.py ios --dynamic
cp -a ./ios/opencv2.framework ./opencv2.framework

Submodule 'opencv' (https://github.com/opencv/opencv.git) registered for path 'opencv'
Submodule path 'opencv': checked out 'a8aff6f64330a0ab2c9d71033412af892dd9b710'
Cloning into 'opencv'...
Executing: ['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_SHARED_LIBS=ON', '-DCMAKE_MACOSX_BUNDLE=ON', '-DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO', '-DIOS_ARCH=armv7;armv7s;arm64', '-DCMAKE_TOOLCHAIN_FILE=/Users/kilpi/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.3-cec70/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/kilpi/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.3-cec70/opencv', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode'] in /Users/kilpi/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.3-cec70/ios/build/build-iphoneos
============================================================
ERROR: [Errno 2] No such file or directory
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 112, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 104, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv/platforms/ios/build_framework.py", line 197, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "opencv/platforms/ios/build_framework.py", line 36, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bcichowlas** [comment]
Happened to me, too, on Mac OS X working for iOS/Swift.  Which file or directory is it not finding?  Is this some sort of permission problem?  Thanks.

**Comment by Lorenzoo81** [comment]
I have the same problem too, someone has solved the problem...?

**Comment by anonym24** [comment]
same error, some time ago with LegoCV it worked ok, but not LegoCV,  not SwiftEyes can't install OpenCVDynamic anymore

**Comment by anonym24** [comment]
it installs ok on previous mac versions, worked for EL Capitan 10.11.6, doesn't work for 10.13 High Sierra..
